config/routes.rb
Rails.application.routes.draw do
    class OnlyAjaxRequest
        def matches?(request)
            request.xhr?
        end
    end

    match 'logic_graph/chronology/:id' => 'logic_graph#chronology', :as => :logic_graph_chronology, via: [:get]
    match 'logic_graph/version/:id' => 'logic_graph#version', :as => :logic_graph_version, via: [:get]

    post 'external/authenticate', as: :login
    post 'external/export', as: :export
    get 'external/logout', :as => :logout

    post 'komet_dashboard/import', as: :import
    get 'komet_dashboard/session_timeout', as: :session_timeout
    get 'komet_dashboard/renew_session', as: :renew_session, :constraints => OnlyAjaxRequest.new

    get 'komet_dashboard/dashboard'
    get 'komet_dashboard/metadata'
    get 'komet_dashboard/version'
    get 'komet_dashboard/get_concept_suggestions'
    get 'komet_dashboard/get_concept_recents'
    get 'komet_dashboard/load_tree_data', :as => :taxonomy_load_tree_data
    get 'komet_dashboard/get_concept_information', :as => :taxonomy_get_concept_information
    get 'komet_dashboard/get_concept_summary', :as => :taxonomy_get_concept_summary
    get 'komet_dashboard/get_concept_sememes', :as => :taxonomy_get_concept_sememes
    get 'komet_dashboard/get_concept_refsets', :as => :taxonomy_get_concept_refsets
    get 'komet_dashboard/get_concept_children', :as => :taxonomy_get_concept_children
    get 'komet_dashboard/get_user_preference_info', :as => :taxonomy_get_user_preference_info
    post 'komet_dashboard/set_coordinates_token', :as => :taxonomy_set_coordinates_token
    get 'komet_dashboard/get_concept_create_info', :as => :taxonomy_get_concept_create_info
    get 'komet_dashboard/get_concept_edit_info', :as => :taxonomy_get_concept_edit_info
    post 'komet_dashboard/create_concept', :as => :taxonomy_create_concept
    post 'komet_dashboard/get_new_property_info', :as => :taxonomy_get_new_property_info
    get 'komet_dashboard/get_generated_vhat_properties', :as => :taxonomy_get_generated_vhat_properties
    post 'komet_dashboard/get_generated_vhat_ids', :as => :taxonomy_get_generated_vhat_ids
    post 'komet_dashboard/edit_concept', :as => :taxonomy_edit_concept
    get 'komet_dashboard/change_concept_state', :as => :taxonomy_change_concept_state

=begin
    get 'workflow/dashboard_workflow', :as => :workflow_dashboard
    post 'workflow/create_workflow', :as => :taxonomy_create_workflow
    get 'workflow/get_history', :as => :workflow_get_history
    get 'workflow/get_transition', :as => :workflow_get_transition
    get 'workflow/get_process', :as => :workflow_get_process
    get 'workflow/set_user_workflow', :as => :workflow_set_user_workflow
    get 'workflow/modal_transition_metadata', :as => :workflow_modal_transition_metadata
    get 'workflow/get_advanceable_process_information', :as => :workflow_get_advanceable_process_information
    post 'workflow/advance_workflow', :as => :workflow_advance_workflow
=end

    get 'search/get_assemblage_suggestions'
    get 'search/get_assemblage_recents'
    get 'search/get_search_results'
    post 'search/get_search_results'

    get 'komet_dashboard/mapping/mapping'
    get 'mapping/load_tree_data'
    get 'mapping/load_mapping_viewer'
    get 'mapping/get_overview_sets_results'
    get 'mapping/get_overview_items_results'
    get 'mapping/map_set_editor'
    post 'mapping/process_map_set'
    post 'mapping/process_map_item'

    root 'external#login'

end

app/controllers/komet_dashboard_controller.rb
=begin
Copyright Notice

 This is a work of the U.S. Government and is not subject to copyright
 protection in the United States. Foreign copyrights may apply.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=end

require './lib/isaac_rest/taxonomy_rest'
require './lib/rails_common/util/controller_helpers'
require './lib/isaac_rest/search_apis_rest'

include ERB::Util

##
# KometDashboardController -
# handles the loading of the taxonomy tree
class KometDashboardController < ApplicationController

    include TaxonomyConcern, ConceptConcern, InstrumentationConcern, SearchApis
    include CommonController, TaxonomyHelper

    #before_action :setup_routes, :setup_constants, :only => [:dashboard] #todo Ask Tim why is this in app controller too?  OK to whack?
    after_filter :byte_size unless Rails.env.production?
    skip_before_action :ensure_roles, only: [:version]
    skip_after_action :verify_authorized, only: [:version]
    skip_before_action :read_only, only: [:version]
    before_action :can_edit_concept, only: [:get_concept_create_info, :create_concept, :edit_concept, :clone_concept, :change_concept_state, :import]
    before_action :can_get_vuids, only: [:get_generated_vhat_ids]

    ##
    # load_tree_data - RESTful route for populating the taxonomy tree using an http :GET
    # The current tree node is identified in the request params with the key :concept_id
    # If the tree is reversed so we are searching for parents of this node is identified in the request params with the key :parent_search (true/false)
    # If the parent of this node was already doing a reverse search is identified in the request params with the key :parent_reversed (true/false)
    # [Object] view_params - various parameters related to the view filters the user wants to apply - see full definition comment at top of komet_dashboard_controller file
    # @return [json] the tree nodes to insert into the tree at the parent node passed in the request
    def load_tree_data

        # TODO - see if some of these can just be referenced everywhere as params[*] instead of passing variables to all sub functions
        selected_concept_id = params[:concept_id]
        parent_search = params[:parent_search]
        parent_reversed = params[:parent_reversed]
        tree_walk_levels = params[:tree_walk_levels]
        multi_path = params[:multi_path]
        next_page = params[:next_page]
        @view_params = check_view_params(params[:view_params])

        # check to make the number of levels to walk the tree was passed in
        if tree_walk_levels == nil
            tree_walk_levels = 1
        else
            tree_walk_levels = tree_walk_levels.to_i
        end

        # check to make sure the flag for exploring multiple parent paths was passed in
        if multi_path == nil
            multi_path = true
        end

        $log.debug("!***! START LOAD TREE DATA PROCESSING")
        tree_nodes = populate_tree(selected_concept_id, parent_search, parent_reversed, tree_walk_levels, multi_path, next_page)
        $log.debug("!***! END LOAD TREE DATA PROCESSING")

        render json: tree_nodes
    end

    def populate_tree(selected_concept_id, parent_search, parent_reversed, tree_walk_levels, multi_path, next_page = nil)

        coordinates_token = session[:coordinates_token].token
        root = selected_concept_id.eql?('#')

        additional_req_params = {coordToken: coordinates_token, sememeMembership: true, maxPageSize: session[:komet_taxonomy_page_size]}
        additional_req_params.merge!(@view_params)

        # check to see if we are getting the next page of child results, if so add the pageNum parameter
        if next_page != nil
            additional_req_params[:pageNum] = next_page
        end

        if boolean(parent_search)
            tree_walk_levels = 100
            additional_req_params[:childDepth] = 0
            additional_req_params[:parentHeight] = tree_walk_levels
        else

            additional_req_params[:childDepth] = tree_walk_levels
            additional_req_params[:parentHeight] = 1
        end

        if root

            # load the ISAAC root node and children
            isaac_concept = TaxonomyRest.get_isaac_root(additional_req_params: additional_req_params)

            if isaac_concept.is_a? CommonRest::UnexpectedResponse
                return []
            end

            inactive_class = ''

            # if the node is inactive apply the correct class
            if isaac_concept.conVersion.state.enumName && isaac_concept.conVersion.state.enumName.downcase.eql?('inactive')
                inactive_class = ' komet-inactive-tree-node'
            end

            terminology_types = get_uuids_from_identified_objects(isaac_concept.terminologyTypes)

            # load the root node into our return variable
            # TODO - remove the hard-coding of type to 'vhat' when the type flags are implemented in the REST APIs
            root_anchor_attributes = { class: 'komet-context-menu' + inactive_class, 'data-menu-type' => 'concept', 'data-menu-uuid' => isaac_concept.conChronology.identifiers.uuids.first,
                                       'data-menu-state' => isaac_concept.conVersion.state.enumName, 'data-menu-concept-text' => isaac_concept.conChronology.description,
                                       'data-menu-concept-terminology-types' => terminology_types, 'data-menu-js-object' => params[:viewer_id]}
            root_node = {id: 0, concept_id: isaac_concept.conChronology.identifiers.uuids.first, text: isaac_concept.conChronology.description, parent_reversed: false, parent_search: parent_search, icon: 'komet-tree-node-icon komet-tree-node-primitive', a_attr: root_anchor_attributes, state: {opened: 'true'}}
        else
            isaac_concept = TaxonomyRest.get_isaac_concept(uuid: selected_concept_id, additional_req_params: additional_req_params)
        end

        if isaac_concept.is_a? CommonRest::UnexpectedResponse
            return []
        end

        $log.debug("!***! START REST CONCEPT PROCESSING")
        raw_nodes = process_rest_concept(isaac_concept, tree_walk_levels, first_level: true, parent_search: parent_search, multi_path: multi_path)
        $log.debug("!***! END REST CONCEPT PROCESSING")

        $log.debug("!***! START TREE LEVEL PROCESSING")
        processed_nodes = process_tree_level(raw_nodes, [], parent_search, parent_reversed)
        $log.debug("!***! END TREE LEVEL PROCESSING")

        if root

            root_node[:children] = processed_nodes
            return [root_node]
        else
            return processed_nodes
        end
    end

    def process_rest_concept(concept, tree_walk_levels, first_level: false, parent_search: false, multi_path: true)

        concept_nodes = []
        has_many_parents = false

        node = {}
        node[:id] = concept.conChronology.identifiers.uuids.first
        node[:text] = concept.conChronology.description
        node[:has_children] = !concept.children.nil?
        node[:has_unfetched_children] = false
        node[:defined] = concept.isConceptDefined
        node[:state] = concept.conVersion.state.enumName
        node[:author] = concept.conVersion.authorUUID
        node[:module] = concept.conVersion.moduleUUID
        node[:path] = concept.conVersion.pathUUID
        node[:refsets] = concept.sememeMembership

        # TODO - remove the hard-coding of type to 'vhat' when the type flags are implemented in the REST APIs
        node[:terminology_types] = get_uuids_from_identified_objects(concept.terminologyTypes)

        if node[:text] == nil
            node[:text] = '[No Description]'
        end

        if node[:defined].nil?
            node[:defined] = false
        end

        if node[:has_children]
            node[:child_count] = concept.children.paginationData.approximateTotal

        elsif tree_walk_levels == 0 && concept.childCount != 0

            node[:child_count] = concept.childCount
            node[:has_children] = true

        else
            node[:child_count] = 0
        end

        node[:has_parents] = !concept.parents.nil?

        if node[:has_parents]
            node[:parent_count] = concept.parents.length

        elsif tree_walk_levels == 0 && concept.parentCount != 0 && boolean(parent_search)

            node[:parent_count] = concept.parentCount
            node[:has_parents] = true

        else
            node[:parent_count] = 0
        end

        if !boolean(parent_search) && node[:child_count] != 0
            node[:badge] = "&nbsp;&nbsp;<span class=\"badge badge-success\" title=\"#{node[:child_count]} children\">#{node[:child_count]}</span>"

        elsif boolean(parent_search) && node[:parent_count] != 0
            node[:badge] = "&nbsp;&nbsp;<span class=\"badge badge-success\" title=\"#{node[:parent_count]} parents\">#{node[:parent_count]}</span>"
        else
            node[:badge] = ''
        end

        node[:parents] = []

        # if this node has parents and we want to see all parent paths then get the details of each parent
        if tree_walk_levels > 0  && !boolean(parent_search) && node[:parent_count] > 1 && boolean(multi_path)

            has_many_parents = true

            if first_level
                node[:badge] = "&nbsp;&nbsp;<span class=\"badge badge-success\" title=\"#{node[:parent_count]} parents\">#{node[:parent_count]}</span>"
            end

            concept.parents.each do |parent|

                parent_node = {}

app/helpers/komet_dashboard_helper.rb
module KometDashboardHelper

  def rest_cache_to_str
    r_val = ""
    $rest_cache.each do |k|
      url  = k.to_a[0]
      r_val << "<b>#{url}</b><br>"
    end
    r_val
  end

end

app/views/komet_dashboard/_user_preferences.html.erb
<div id="komet_user_preference_form">
    <div id="komet_preferences_tabs" role="tab">
        <ul>
            <li><a href='#komet_preferences_general_tab'>General Options</a></li>
            <li><a href='#komet_preferences_module_tab'>Module Flags</a></li>
            <li><a href='#komet_preferences_path_tab'>Path Flags</a></li>
            <li><a href='#komet_preferences_refset_tab'>Refset Flags</a></li>
        </ul>

        <form action="<%= taxonomy_set_coordinates_token_path %>">

            <div id="komet_preferences_general_tab">

                <div class="komet-row">
                    <label for="komet_preferences_language" class="komet-preference-label">Select Language:</label>
                    <%= select_tag :komet_preferences_language, options_for_select(session[:komet_language_options], @language_coordinate), class: 'form-control', 'aria-label' => 'Select Language' %>
                </div>

                <div class="komet-row">

                    <label for="komet_preferences_stamp_date_field" class="komet-preference-label">STAMP as of Date:</label>

                    <div class='input-group date' id='komet_preferences_stamp_date'>
                        <input type='text' id="komet_preferences_stamp_date_field" name="time" class="form-control" aria-label="STAMP Date">
                        <span class="input-group-addon">
                            <span class="fa fa-calendar"></span>
                        </span>
                    </div>

                </div>

                <div class="komet-row">

                    <div class="komet-label komet-preference-label">Allowed States:</div>

                    <div>
                        <input type="radio" id="komet_allowed_states_both" name="allowed_states" aria-label="Show All States" value="active,inactive"> <label for="komet_allowed_states_both">All</label>
                        <input type="radio" id="komet_allowed_states_active" name="allowed_states" aria-label="Show Active States" value="active" class="komet-indent-block"> <label for="komet_allowed_states_active">Active</label>
                    </div>

                </div>

                <div class="komet-row">

                    <div class="komet-label komet-preference-label">Auto Assign VUID:</div>

                    <div>
                        <input type="radio" id="komet_generate_vuid_true" name="generate_vuid" aria-label="Auto Assign VUID On" value="true"> <label for="komet_generate_vuid_true">On</label>
                        <input type="radio" id="komet_generate_vuid_false" name="generate_vuid" aria-label="Auto Assign VUID Off" value="false" class="komet-indent-block"> <label for="komet_generate_vuid_false">Off</label>
                    </div>

                </div>

                <div class="komet-row">

                    <div class="komet-label komet-preference-label">Taxonomy Tree Page Size:</div>

                    <div>
                        <%= select_tag :komet_preferences_taxonomy_page_size, options_for_select([['250'], ['500'], ['1000']], session[:komet_taxonomy_page_size]), class: 'form-control', 'aria-label' => 'Select Taxonomy Tree Page Size' %>
                    </div>

                </div>

                <!-- start Description Type order control -->
                <div class="komet-row komet-order-control-header komet-table-header">
                    <div class="komet-order-control-rank">Rank</div>
                    <div class="komet-order-control-text">Description Type</div>
                </div>

                <div class="komet-order-control-body komet-table-body">

                    <% @description_type_options.each do |description_type| %>

                        <div class="komet-row">

                            <div class="komet-order-control-rank">

                                <button type="button" class="komet-link-button komet-change-order komet-change-order-up" onclick="UIHelper.moveRowOrderControl(this, 'up')" aria-label="Move <%= description_type[:text] %> Rank Up" title="Move Up">
                                    <div class="glyphicon glyphicon-arrow-up"></div>
                                </button>

                                <button type="button" class="komet-link-button komet-change-order komet-change-order-down" onclick="UIHelper.moveRowOrderControl(this, 'down')" aria-label="Move <%= description_type[:text] %> Rank Down" title="Move Down">
                                    <div class="glyphicon glyphicon-arrow-down"></div>
                                </button>

                            </div>

                            <div class="komet-order-control-text">
                                <%= description_type[:text] %>
                                <input type="hidden" name="description_type[<%= description_type[:concept_sequence] %>]" value="<%= description_type[:concept_sequence] %>" />
                            </div>

                        </div>

                    <% end %>
                </div>
                <!-- end Description Type order control -->

                <!-- start Dialect order control -->
                <div class="komet-row komet-order-control-header komet-table-header">
                    <div class="komet-order-control-rank">Rank</div>
                    <div class="komet-order-control-text">Dialect</div>
                </div>

                <div class="komet-order-control-body komet-table-body">

                    <% @dialect_options.each do |dialect| %>

                        <div class="komet-row">

                            <div class="komet-order-control-rank">

                                <button type="button" class="komet-link-button komet-change-order komet-change-order-up" onclick="UIHelper.moveRowOrderControl(this, 'up')" aria-label="Move <%= dialect[:text] %> Rank Up" title="Move Up">
                                    <div class="glyphicon glyphicon-arrow-up"></div>
                                </button>

                                <button type="button" class="komet-link-button komet-change-order komet-change-order-down" onclick="UIHelper.moveRowOrderControl(this, 'down')" aria-label="Move <%= dialect[:text] %> Rank Down" title="Move Down">
                                    <div class="glyphicon glyphicon-arrow-down"></div>
                                </button>

                            </div>

                            <div class="komet-order-control-text">
                                <%= dialect[:text] %>
                                <input type="hidden" name="dialect[<%= dialect[:concept_sequence] %>]" value="<%= dialect[:concept_sequence] %>" />
                            </div>

                        </div>

                    <% end %>
                </div>
                <!-- end Description Type order control -->

            </div>

            <!-- start Module Flags section -->
            <div id="komet_preferences_module_tab">

                <!-- add the flag control widget for modules -->
                <%= render(partial: 'komet_dashboard/flag_control_template', locals: {
                    flag_data: @module_flags,
                    field_id_prefix: 'komet_preferences_module',
                    field_name_prefix: 'module_flags',
                    flag_item_header: 'Module'
                }) %>

            </div>

            <div id="komet_preferences_path_tab">

                <!-- add the flag control widget for paths -->
                <%= render(partial: 'komet_dashboard/flag_control_template', locals: {
                    flag_data: @path_flags,
                    field_id_prefix: 'komet_preferences_path',
                    field_name_prefix: 'path_flags',
                    flag_item_header: 'Path'
                }) %>

            </div>

            <div id="komet_preferences_refset_tab">

                <!-- add the flag control widget for paths -->
                <%= render(partial: 'komet_dashboard/flag_control_template', locals: {
                    flag_data: @refset_flags,
                    field_id_prefix: 'komet_preferences_refset',
                    field_name_prefix: 'refset_flags',
                    flag_item_header: 'Refset',
                    use_template_rows: true
                }) %>

            </div>

        </form>
    </div>
</div>
<script>
    $(document).ready(function () {

        $("#komet_allowed_states_<%= @allowed_states %>")[0].checked = true;
        $("#komet_generate_vuid_<%= @generate_vuid %>")[0].checked = true;
        $("#komet_preferences_path_tab").find('.komet_color_picker').minicolors();
        PreferenceModule.initialize("<%= @stamp_date%>");
    });
</script>

app/views/komet_dashboard/_userspreference.html.erb
<div id="komet_user_preference_form">
    <div id="komet_preferences_tabs" role="tab">
        <ul>
            <li><a href='#komet_preferences_general_tab'>General Options</a></li>
            <li><a href='#komet_preferences_module_tab'>Module Flags</a></li>
            <li><a href='#komet_preferences_path_tab'>Path Flags</a></li>
            <li><a href='#komet_preferences_refset_tab'>Refset Flags</a></li>
        </ul>

        <form action="<%= taxonomy_set_coordinates_token_path %>">

            <div id="komet_preferences_general_tab">

                <div class="komet-row">
                    <label for="komet_preferences_language" class="komet-preference-label">Select Language:</label>
                    <%= select_tag :komet_preferences_language, options_for_select(session[:komet_language_options], @language_coordinate), class: 'form-control', 'aria-label' => 'Select Language' %>
                </div>

                <div class="komet-row">

                    <label for="komet_preferences_stamp_date_field" class="komet-preference-label">STAMP as of Date:</label>

                    <div class='input-group date' id='komet_preferences_stamp_date'>
                        <input type='text' id="komet_preferences_stamp_date_field" name="time" class="form-control" aria-label="STAMP Date">
                        <span class="input-group-addon">
                            <span class="fa fa-calendar"></span>
                        </span>
                    </div>

                </div>

                <div class="komet-row">

                    <div class="komet-label komet-preference-label">Allowed States:</div>

                    <div>
                        <input type="radio" id="komet_allowed_states_both" name="allowed_states" aria-label="Show All States" value="active,inactive"> <label for="komet_allowed_states_both">All</label>
                        <input type="radio" id="komet_allowed_states_active" name="allowed_states" aria-label="Show Active States" value="active" class="komet-indent-block"> <label for="komet_allowed_states_active">Active</label>
                    </div>

                </div>

                <!-- start Description Type order control -->
                <div class="komet-row komet-order-control-header">
                    <div class="komet-order-control-rank">Rank</div>
                    <div class="komet-order-control-text">Description Type</div>
                </div>

                <div class="komet-order-control-body">

                    <% @description_type_options.each do |description_type| %>

                        <div class="komet-row">

                            <div class="komet-order-control-rank">

                                <button type="button" class="komet-link-button komet-change-order komet-change-order-up" onclick="UIHelper.moveRowOrderControl(this, 'up')" aria-label="Move <%= description_type[:text] %> Rank Up" title="Move Up">
                                    <div class="glyphicon glyphicon-arrow-up"></div>
                                </button>

                                <button type="button" class="komet-link-button komet-change-order komet-change-order-down" onclick="UIHelper.moveRowOrderControl(this, 'down')" aria-label="Move <%= description_type[:text] %> Rank Down" title="Move Down">
                                    <div class="glyphicon glyphicon-arrow-down"></div>
                                </button>

                            </div>

                            <div class="komet-order-control-text">
                                <%= description_type[:text] %>
                                <input type="hidden" name="description_type[<%= description_type[:concept_sequence] %>]" value="<%= description_type[:concept_sequence] %>" />
                            </div>

                        </div>

                    <% end %>
                </div>
                <!-- end Description Type order control -->

                <!-- start Dialect order control -->
                <div class="komet-row komet-order-control-header">
                    <div class="komet-order-control-rank">Rank</div>
                    <div class="komet-order-control-text">Dialect</div>
                </div>

                <div class="komet-order-control-body">

                    <% @dialect_options.each do |dialect| %>

                        <div class="komet-row">

                            <div class="komet-order-control-rank">

                                <button type="button" class="komet-link-button komet-change-order komet-change-order-up" onclick="UIHelper.moveRowOrderControl(this, 'up')" aria-label="Move <%= dialect[:text] %> Rank Up" title="Move Up">
                                    <div class="glyphicon glyphicon-arrow-up"></div>
                                </button>

                                <button type="button" class="komet-link-button komet-change-order komet-change-order-down" onclick="UIHelper.moveRowOrderControl(this, 'down')" aria-label="Move <%= dialect[:text] %> Rank Down" title="Move Down">
                                    <div class="glyphicon glyphicon-arrow-down"></div>
                                </button>

                            </div>

                            <div class="komet-order-control-text">
                                <%= dialect[:text] %>
                                <input type="hidden" name="dialect[<%= dialect[:concept_sequence] %>]" value="<%= dialect[:concept_sequence] %>" />
                            </div>

                        </div>

                    <% end %>
                </div>
                <!-- end Description Type order control -->

            </div>

            <!-- start Module Flags section -->
            <div id="komet_preferences_module_tab">

                <!-- add the flag control widget for modules -->
                <%= render(partial: 'komet_dashboard/flag_control_template', locals: {
                    flag_data: @module_flags,
                    field_id_prefix: 'komet_preferences_module',
                    field_name_prefix: 'module_flags',
                    flag_item_header: 'Module'
                }) %>

            </div>

            <div id="komet_preferences_path_tab">

                <!-- add the flag control widget for paths -->
                <%= render(partial: 'komet_dashboard/flag_control_template', locals: {
                    flag_data: @path_flags,
                    field_id_prefix: 'komet_preferences_path',
                    field_name_prefix: 'path_flags',
                    flag_item_header: 'Path'
                }) %>

            </div>

            <div id="komet_preferences_refset_tab">

                <!-- add the flag control widget for paths -->
                <%= render(partial: 'komet_dashboard/flag_control_template', locals: {
                    flag_data: @refset_flags,
                    field_id_prefix: 'komet_preferences_refset',
                    field_name_prefix: 'refset_flags',
                    flag_item_header: 'Refset',
                    use_template_rows: true
                }) %>

            </div>

        </form>
    </div>
</div>
<script>
    $(document).ready(function () {

        $("#komet_allowed_states_<%= @allowed_states %>")[0].checked = true;
        $("#komet_preferences_path_tab").find('.komet_color_picker').minicolors();
        PreferenceModule.initialize("<%= @stamp_date%>");
    });
</script>

app/views/komet_dashboard/metadata.html.erb
<h1>KometDashboard#metadata</h1>
<p>Rails root is: <%=Rails.root%></p>
<p>Rails environment is <%=Rails.env%></p>
<p>Environment variable RAILS_SERVE_STATIC_FILES=<%=ENV['RAILS_SERVE_STATIC_FILES']%></p>
<p>Environment variable RAILS_RELATIVE_URL_ROOT=<%=ENV['RAILS_RELATIVE_URL_ROOT']%></p>
<p>Rails root_path is? <%=root_path%></p>
<p>Rails pid is? <%=$$.to_s%></p>
<%unless Rails.env.production?%>
    <%= raw "<p>Rest cache has a size of #{$rest_cache.to_a.length}<br>"%>
    <%= raw rest_cache_to_str%>
<%end%>