config/routes.rb
Rails.application.routes.draw do
    class OnlyAjaxRequest
        def matches?(request)
            request.xhr?
        end
    end

    match 'logic_graph/chronology/:id' => 'logic_graph#chronology', :as => :logic_graph_chronology, via: [:get]
    match 'logic_graph/version/:id' => 'logic_graph#version', :as => :logic_graph_version, via: [:get]

    post 'external/authenticate', as: :login
    post 'external/export', as: :export
    get 'external/logout', :as => :logout

    post 'komet_dashboard/import', as: :import
    get 'komet_dashboard/session_timeout', as: :session_timeout
    get 'komet_dashboard/renew_session', as: :renew_session, :constraints => OnlyAjaxRequest.new

    get 'komet_dashboard/dashboard'
    get 'komet_dashboard/metadata'
    get 'komet_dashboard/version'
    get 'komet_dashboard/get_concept_suggestions'
    get 'komet_dashboard/get_concept_recents'
    get 'komet_dashboard/load_tree_data', :as => :taxonomy_load_tree_data
    get 'komet_dashboard/get_concept_information', :as => :taxonomy_get_concept_information
    get 'komet_dashboard/get_concept_summary', :as => :taxonomy_get_concept_summary
    get 'komet_dashboard/get_concept_sememes', :as => :taxonomy_get_concept_sememes
    get 'komet_dashboard/get_concept_refsets', :as => :taxonomy_get_concept_refsets
    get 'komet_dashboard/get_concept_children', :as => :taxonomy_get_concept_children
    get 'komet_dashboard/get_user_preference_info', :as => :taxonomy_get_user_preference_info
    post 'komet_dashboard/set_coordinates_token', :as => :taxonomy_set_coordinates_token
    get 'komet_dashboard/get_concept_create_info', :as => :taxonomy_get_concept_create_info
    get 'komet_dashboard/get_concept_edit_info', :as => :taxonomy_get_concept_edit_info
    post 'komet_dashboard/create_concept', :as => :taxonomy_create_concept
    post 'komet_dashboard/get_new_property_info', :as => :taxonomy_get_new_property_info
    get 'komet_dashboard/get_generated_vhat_properties', :as => :taxonomy_get_generated_vhat_properties
    post 'komet_dashboard/get_generated_vhat_ids', :as => :taxonomy_get_generated_vhat_ids
    post 'komet_dashboard/edit_concept', :as => :taxonomy_edit_concept
    get 'komet_dashboard/change_concept_state', :as => :taxonomy_change_concept_state

=begin
    get 'workflow/dashboard_workflow', :as => :workflow_dashboard
    post 'workflow/create_workflow', :as => :taxonomy_create_workflow
    get 'workflow/get_history', :as => :workflow_get_history
    get 'workflow/get_transition', :as => :workflow_get_transition
    get 'workflow/get_process', :as => :workflow_get_process
    get 'workflow/set_user_workflow', :as => :workflow_set_user_workflow
    get 'workflow/modal_transition_metadata', :as => :workflow_modal_transition_metadata
    get 'workflow/get_advanceable_process_information', :as => :workflow_get_advanceable_process_information
    post 'workflow/advance_workflow', :as => :workflow_advance_workflow
=end

    get 'search/get_assemblage_suggestions'
    get 'search/get_assemblage_recents'
    get 'search/get_search_results'
    post 'search/get_search_results'

    get 'komet_dashboard/mapping/mapping'
    get 'mapping/load_tree_data'
    get 'mapping/load_mapping_viewer'
    get 'mapping/get_overview_sets_results'
    get 'mapping/get_overview_items_results'
    get 'mapping/map_set_editor'
    post 'mapping/process_map_set'
    post 'mapping/process_map_item'

    root 'external#login'

end

app/controllers/komet_dashboard_controller.rb
=begin
Copyright Notice

 This is a work of the U.S. Government and is not subject to copyright
 protection in the United States. Foreign copyrights may apply.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=end

require './lib/isaac_rest/taxonomy_rest'
require './lib/rails_common/util/controller_helpers'
require './lib/isaac_rest/search_apis_rest'

include ERB::Util

##
# KometDashboardController -
# handles the loading of the taxonomy tree
class KometDashboardController < ApplicationController

    include TaxonomyConcern, ConceptConcern, InstrumentationConcern, SearchApis
    include CommonController, TaxonomyHelper

    #before_action :setup_routes, :setup_constants, :only => [:dashboard] #todo Ask Tim why is this in app controller too?  OK to whack?
    after_filter :byte_size unless Rails.env.production?
    skip_before_action :ensure_roles, only: [:version]
    skip_after_action :verify_authorized, only: [:version]
    skip_before_action :read_only, only: [:version]
    before_action :can_edit_concept, only: [:get_concept_create_info, :create_concept, :edit_concept, :clone_concept, :change_concept_state, :import]
    before_action :can_get_vuids, only: [:get_generated_vhat_ids]

    ##
    # load_tree_data - RESTful route for populating the taxonomy tree using an http :GET
    # The current tree node is identified in the request params with the key :concept_id
    # If the tree is reversed so we are searching for parents of this node is identified in the request params with the key :parent_search (true/false)
    # If the parent of this node was already doing a reverse search is identified in the request params with the key :parent_reversed (true/false)
    # [Object] view_params - various parameters related to the view filters the user wants to apply - see full definition comment at top of komet_dashboard_controller file
    # @return [json] the tree nodes to insert into the tree at the parent node passed in the request
    def load_tree_data

        # TODO - see if some of these can just be referenced everywhere as params[*] instead of passing variables to all sub functions
        selected_concept_id = params[:concept_id]
        parent_search = params[:parent_search]
        parent_reversed = params[:parent_reversed]
        tree_walk_levels = params[:tree_walk_levels]
        multi_path = params[:multi_path]
        next_page = params[:next_page]
        @view_params = check_view_params(params[:view_params])

        # check to make the number of levels to walk the tree was passed in
        if tree_walk_levels == nil
            tree_walk_levels = 1
        else
            tree_walk_levels = tree_walk_levels.to_i
        end

        # check to make sure the flag for exploring multiple parent paths was passed in
        if multi_path == nil
            multi_path = true
        end

        $log.debug("!***! START LOAD TREE DATA PROCESSING")
        tree_nodes = populate_tree(selected_concept_id, parent_search, parent_reversed, tree_walk_levels, multi_path, next_page)
        $log.debug("!***! END LOAD TREE DATA PROCESSING")

        render json: tree_nodes
    end

    def populate_tree(selected_concept_id, parent_search, parent_reversed, tree_walk_levels, multi_path, next_page = nil)

        coordinates_token = session[:coordinates_token].token
        root = selected_concept_id.eql?('#')

        additional_req_params = {coordToken: coordinates_token, sememeMembership: true, maxPageSize: session[:komet_taxonomy_page_size]}
        additional_req_params.merge!(@view_params)

        # check to see if we are getting the next page of child results, if so add the pageNum parameter
        if next_page != nil
            additional_req_params[:pageNum] = next_page
        end

        if boolean(parent_search)
            tree_walk_levels = 100
            additional_req_params[:childDepth] = 0
            additional_req_params[:parentHeight] = tree_walk_levels
        else

            additional_req_params[:childDepth] = tree_walk_levels
            additional_req_params[:parentHeight] = 1
        end

        if root

            # load the ISAAC root node and children
            isaac_concept = TaxonomyRest.get_isaac_root(additional_req_params: additional_req_params)

            if isaac_concept.is_a? CommonRest::UnexpectedResponse
                return []
            end

            inactive_class = ''

            # if the node is inactive apply the correct class
            if isaac_concept.conVersion.state.enumName && isaac_concept.conVersion.state.enumName.downcase.eql?('inactive')
                inactive_class = ' komet-inactive-tree-node'
            end

            terminology_types = get_uuids_from_identified_objects(isaac_concept.terminologyTypes)

            # load the root node into our return variable
            # TODO - remove the hard-coding of type to 'vhat' when the type flags are implemented in the REST APIs
            root_anchor_attributes = { class: 'komet-context-menu' + inactive_class, 'data-menu-type' => 'concept', 'data-menu-uuid' => isaac_concept.conChronology.identifiers.uuids.first,
                                       'data-menu-state' => isaac_concept.conVersion.state.enumName, 'data-menu-concept-text' => isaac_concept.conChronology.description,
                                       'data-menu-concept-terminology-types' => terminology_types, 'data-menu-js-object' => params[:viewer_id]}
            root_node = {id: 0, concept_id: isaac_concept.conChronology.identifiers.uuids.first, text: isaac_concept.conChronology.description, parent_reversed: false, parent_search: parent_search, icon: 'komet-tree-node-icon komet-tree-node-primitive', a_attr: root_anchor_attributes, state: {opened: 'true'}}
        else
            isaac_concept = TaxonomyRest.get_isaac_concept(uuid: selected_concept_id, additional_req_params: additional_req_params)
        end

        if isaac_concept.is_a? CommonRest::UnexpectedResponse
            return []
        end

        $log.debug("!***! START REST CONCEPT PROCESSING")
        raw_nodes = process_rest_concept(isaac_concept, tree_walk_levels, first_level: true, parent_search: parent_search, multi_path: multi_path)
        $log.debug("!***! END REST CONCEPT PROCESSING")

        $log.debug("!***! START TREE LEVEL PROCESSING")
        processed_nodes = process_tree_level(raw_nodes, [], parent_search, parent_reversed)
        $log.debug("!***! END TREE LEVEL PROCESSING")

        if root

            root_node[:children] = processed_nodes
            return [root_node]
        else
            return processed_nodes
        end
    end

    def process_rest_concept(concept, tree_walk_levels, first_level: false, parent_search: false, multi_path: true)

        concept_nodes = []
        has_many_parents = false

        node = {}
        node[:id] = concept.conChronology.identifiers.uuids.first
        node[:text] = concept.conChronology.description
        node[:has_children] = !concept.children.nil?
        node[:has_unfetched_children] = false
        node[:defined] = concept.isConceptDefined
        node[:state] = concept.conVersion.state.enumName
        node[:author] = concept.conVersion.authorUUID
        node[:module] = concept.conVersion.moduleUUID
        node[:path] = concept.conVersion.pathUUID
        node[:refsets] = concept.sememeMembership

        # TODO - remove the hard-coding of type to 'vhat' when the type flags are implemented in the REST APIs
        node[:terminology_types] = get_uuids_from_identified_objects(concept.terminologyTypes)

        if node[:text] == nil
            node[:text] = '[No Description]'
        end

        if node[:defined].nil?
            node[:defined] = false
        end

        if node[:has_children]
            node[:child_count] = concept.children.paginationData.approximateTotal

        elsif tree_walk_levels == 0 && concept.childCount != 0

            node[:child_count] = concept.childCount
            node[:has_children] = true

        else
            node[:child_count] = 0
        end

        node[:has_parents] = !concept.parents.nil?

        if node[:has_parents]
            node[:parent_count] = concept.parents.length

        elsif tree_walk_levels == 0 && concept.parentCount != 0 && boolean(parent_search)

            node[:parent_count] = concept.parentCount
            node[:has_parents] = true

        else
            node[:parent_count] = 0
        end

        if !boolean(parent_search) && node[:child_count] != 0
            node[:badge] = "&nbsp;&nbsp;<span class=\"badge badge-success\" title=\"#{node[:child_count]} children\">#{node[:child_count]}</span>"

        elsif boolean(parent_search) && node[:parent_count] != 0
            node[:badge] = "&nbsp;&nbsp;<span class=\"badge badge-success\" title=\"#{node[:parent_count]} parents\">#{node[:parent_count]}</span>"
        else
            node[:badge] = ''
        end

        node[:parents] = []

        # if this node has parents and we want to see all parent paths then get the details of each parent
        if tree_walk_levels > 0  && !boolean(parent_search) && node[:parent_count] > 1 && boolean(multi_path)

            has_many_parents = true

            if first_level
                node[:badge] = "&nbsp;&nbsp;<span class=\"badge badge-success\" title=\"#{node[:parent_count]} parents\">#{node[:parent_count]}</span>"
            end

            concept.parents.each do |parent|

                parent_node = {}

app/helpers/komet_dashboard_helper.rb
module KometDashboardHelper

  def rest_cache_to_str
    r_val = ""
    $rest_cache.each do |k|
      url  = k.to_a[0]
      r_val << "<b>#{url}</b><br>"
    end
    r_val
  end

end

app/views/komet_dashboard/concept_detail/_concept_add.html.erb
<div class="panel panel-default komet-no-margins komet-panel komet-concept-create" id="komet_viewer_<%= @viewer_id %>" data-komet-viewer-id="<%= @viewer_id %>">
    <!-- DO NOT PUT ANYTHING ABOVE THE KOMET VIEWER DIV - IT WILL BREAK WINDOWING WHEN CLOSING VIEWERS AND BE REPEATED EVERY TIME NEW CONTENT IS LOADED TO INLINE VIEWER -->

    <%= form_tag(taxonomy_create_concept_path, method: 'post', id: "komet_concept_editor_form_#{@viewer_id}") do %>

        <div class="panel-heading">
            <span class="panel-title komet-section-title">
                <button type="button" class="komet-link-button" onclick="WindowManager.toggleViewerLinkage('<%= @viewer_id %>', WindowManager.getLinkedViewerID() != '<%= @viewer_id %>');" aria-label="Viewer linked to Taxonomy Tree. Click to unlink." title="Viewer linked to Taxonomy Tree. Click to unlink.">
                    <span id="komet_concept_panel_tree_link_<%= @viewer_id %>" class="fa fa-chain-broken" ></span>
                </button>
                New Concept
            </span>

            <div class="komet-panel-tools-control hide">
                <div id='komet_concept_stamp_date_<%= @viewer_id %>'>
                    <input type='hidden' value="<%= @view_params[:time] %>">
                </div>
                <input id='komet_concept_stated_<%= @viewer_id %>' type='hidden' value="<%= @view_params[:stated] %>">
                <input id='komet_concept_allowed_states_<%= @viewer_id %>' type='hidden' value="<%= @view_params[:allowedStates] %>">
                <input id='komet_concept_modules_<%= @viewer_id %>' type='hidden' value="<%= @view_params[:modules] %>">
                <input id='komet_concept_path_<%= @viewer_id %>' type='hidden' value="<%= @view_params[:path] %>">
            </div>

            <div class="komet-panel-tools">
                <button type="button" class="komet-link-button" aria-label="Close Viewer" onclick="WindowManager.closeViewer('<%= @viewer_id %>')" title="Close Viewer">
                    <div class="komet-action-icon glyphicon glyphicon-remove"></div>
                </button>
            </div>
        </div>

        <div class="panel-body" id="komet_concept_editor_section_<%= @viewer_id %>">

            <div id="komet_concept_save_section_<%= @viewer_id %>">
                All fields required except where noted as Optional.
                <button type="button" class="btn btn-default" onclick="WindowManager.cancelEditMode('<%= @viewer_id %>')">Cancel</button>
                <button type="button" class="btn btn-primary ui-state-disabled" disabled id="komet_concept_save_<%= @viewer_id %>" onclick="WindowManager.viewers[<%= @viewer_id %>].showSaveSection('confirm')">Save</button>
            </div>

            <div class="komet-concept-section-title komet-concept-associations-title">RELATIONSHIPS</div>

            <div id="komet_concept_associations_panel_<%= @viewer_id %>" class="komet-concept-section-panel komet-concept-associations-panel">
                <div class="komet-concept-section-panel-details komet-changeable">
                    <autosuggest
                        id-base="komet_create_concept_parent"
                        id-postfix="_<%= @viewer_id %>"
                        label="Has Parent"
                        value="<%= @parent_id %>"
                        display-value="<%= @parent_text %>"
                        terminology-types="<%= @parent_terminology_types %>"
                        suggestion-onchange-function="WindowManager.viewers[<%= @viewer_id %>].conceptEditorParentOnChange()"
                    ></autosuggest>
                </div>
            </div>

            <div class="komet-concept-section-title komet-concept-description-title">DESIGNATIONS</div>

            <div id="komet_concept_description_panel_<%= @viewer_id %>" class="komet-concept-section-panel komet-concept-description-panel">

                <div class="komet-concept-section-panel-details">

                    <div class="komet-changeable">
                        <select name="komet_create_concept_description_type" id="komet_create_concept_description_type_<%= @viewer_id %>" class="form-control" aria-label="Designation Type" title="Designation Type">

                            <% @description_types.each do |type| %>

                                <!-- replace with the metadata value when available-->
                                <option value="<%= type[:concept_id] %>" <% if type[:concept_id] == '7b402b1e-5587-5732-80bf-69be40426df3' %> selected <% end %>>
                                    <%= type[:description] %>
                                </option>
                            <% end %>

                        </select>
                        <input name="komet_create_concept_description" id="komet_create_concept_description_<%= @viewer_id %>" class="form-control" aria-label="Designation Text" title="Designation Text">
                    </div>


                </div>
            </div>
        </div>
    <% end # end form %>

    <script>

        if (!WindowManager.viewers.hasOwnProperty('<%= @viewer_id %>') || !(WindowManager.viewers[<%= @viewer_id %>] instanceof ConceptViewer)) {
            ConceptsModule.createViewer("<%= @viewer_id %>", null, "<%= @viewer_action %>", null, <%= raw session['komet_extended_description_types'].to_json %>);
        } else {

            WindowManager.viewers[<%= @viewer_id %>].initConcept(null, "<%= @viewer_action %>", null, <%= raw session['komet_extended_description_types'].to_json %>);

            if (WindowManager.getLinkedViewerID() == "<%= @viewer_id %>") {
                WindowManager.viewers["<%= @viewer_id %>"].swapLinkIcon(true);
            }
        }

        $(document).ready(function () {

            WindowManager.viewers[<%= @viewer_id %>].createConcept();
            UIHelper.initializeContextMenus();
        });
    </script>

    <!-- DO NOT PUT ANYTHING ABOVE THE BELOW THIS LAST DIV - IT WILL GET REPEATED EVERY TIME NEW CONTENT IS LOADED TO INLINE VIEWER-->
</div>

app/views/komet_dashboard/concept_detail/_concept_attributes.html.erb
<div class="komet-concept-section-title komet-concept-attributes-title">CONCEPT</div>

<div id="komet_concept_attributes_panel_<%= @viewer_id %>" class="komet-concept-section-panel komet-concept-attributes-panel">

    <!-- main header block - always visible -->
    <div class="komet-concept-section-panel-header">

        <% if @concept_state != '' %>
            <!-- expand/collapse icon - controls details drawer -->
            <button type="button" class="komet-link-button" onclick="WindowManager.viewers[<%= @viewer_id %>].togglePanelDetails('komet_concept_attributes_panel_<%= @viewer_id %>', null, true)" aria-label="Expand Concept Section" title="Expand Concept Section">
                <div class="glyphicon glyphicon-plus-sign"></div>
            </button>
        <% end %>

        <!-- Status -->
        <div class="komet-concept-attributes-status">
            <%= @concept_state %>
        </div>

        <!-- Defined -->
        <div class="komet-containing-block">
            <% if @concept_defined == 'Primitive' %>
                <div class="komet-tree-node-icon komet-tree-node-primitive" title="<%= @concept_defined %>"></div> &nbsp; <%= @concept_defined %>
            <% else %>
                <div class="komet-tree-node-icon komet-tree-node-defined" title="<%= @concept_defined %>"></div> &nbsp; <%= @concept_defined %>
            <% end %>
        </div>

    </div>

    <!-- details drawer - can be collapsed -->
    <div class="komet-concept-section-panel-details">

        <div class="komet-concept-attributes-details-row">

            <div class="komet-concept-attributes-details-name">
                <b>UUID:</b> <%= @concept_id %>
            </div>

        </div>

        <% if @terminology_id %>

            <hr class="komet-concept-details-hr" />

            <div class="komet-concept-attributes-details-row">

                <div class="komet-concept-attributes-details-name">
                    <b><%= @terminology_id[:label] %>:</b> <%= @terminology_id[:value] %>
                </div>

            </div>

        <% end %>

        <!-- loop through the attributes attributes -->
        <% @attributes.each_with_index do |attribute, attribute_index| %>

            <hr class="komet-concept-details-hr" />

            <div class="komet-concept-attributes-details-row">

                <div class="komet-concept-attributes-details-name">
                    <b><%= attribute[:label] %>:</b> <%= attribute[:value] %>
                </div>

            </div>

        <% end %>



            <!-- loop through the description nested properties -->
            <% @concept_sememes[:rows].each_with_index do |property, property_index| %>

                <hr class="komet-concept-details-hr" />

                <div class="komet-row">

                    <div class="komet-concept-attributes-details-name">
                        <b><%= property[:sememe_name] %></b>
                    </div>

                    <% property[:columns].each do |column_id, column_data| %>

                        <div class="komet-concept-attributes-details-item">
                            <b><%= @concept_sememes[:field_info][column_id][:name] %>:</b>

                            <!-- if this row has a display value show that in place of the row data and put a tooltip to show the row data, otherwise just show the data -->
                            <% if column_data[:display] == '' %>

                                <%= column_data[:data] %>

                            <% else %>

                                    <span class="komet-context-menu" data-menu-js-object="<%= @viewer_id %>" data-menu-type="sememe" data-menu-uuid="<%= column_data[:data] %>" title="<%= column_data[:data] %>">
                                        <%= column_data[:display] %>
                                    </span>

                            <% end %>
                        </div>

                    <% end %>

                </div>

            <% end %>

    </div>

</div>

<script>
    WindowManager.viewers[<%= @viewer_id %>].setPanelState('komet_concept_attributes_panel_<%= @viewer_id %>', null, null);
</script>

app/views/komet_dashboard/concept_detail/_concept_descriptions.html.erb
<div class="komet-concept-section-title komet-concept-description-title">DESCRIPTIONS</div>

<% @descriptions.descriptions.each do |description| %>

    <div id="komet_concept_description_panel_<%= @viewer_id %>_<%= description[:description_id] %>" class="komet-concept-section-panel komet-concept-description-panel">

        <!-- main header block - always visible -->
        <div class="komet-concept-section-panel-header komet-concept-description-panel-header">

            <!-- expand/collapse icon - controls details drawer -->
            <button type="button" class="komet-link-button" onclick="WindowManager.viewers[<%= @viewer_id %>].togglePanelDetails('komet_concept_description_panel_<%= @viewer_id %>_<%= description[:description_id] %>')" aria-label="Expand Description Section" title="Expand Description Section">
                <div class="glyphicon glyphicon-plus-sign"></div>
            </button>

            <div class="komet-concept-description-header-block">

                <!-- description text -->
                <div class="komet-concept-description-text komet-context-menu"
                     data-menu-type="concept"
                     data-menu-uuid="<%= description[:description_id] %>"
                     data-menu-concept-text="<%= description[:text] %>"
                     data-menu-concept-terminology-types="<%= description[:terminology_type] %>"
                     data-menu-state="<%= description[:state] %>"
                     data-menu-js-object="<%= @viewer_id %>"
                >
                    <b><%= description[:text] %></b>
                </div>

                <!-- description type, refset, case sensitive, state -->
                <div class="komet-concept-description-info">

                    <span class="komet-concept-description-title" title="<%= description[:description_type] %>">
                        <%= description[:description_type_short] %>
                    </span>

                    <!-- get the case significance and display an appropriate icon -->
                    <% if description[:case_significance_short] == 'true' %>

                        <span class="glyphicon glyphicon-text-size" title="<%= description[:case_significance] %>"></span>

                    <% else %>

                        <span class="komet-icon-stack" title="<%= description[:case_significance] %>">
                          <span class="glyphicon glyphicon-text-size komet-icon-stack-base"></span>
                          <span class="glyphicon glyphicon-ban-circle"></span>
                        </span>

                    <% end %>

                    <span><%= description[:state] %></span>
                    <span title="<%= description[:language] %>"><%= description[:language_short] %></span>
                    <span> - <%= description[:header_dialects] %></span>

                    </div>

            </div>
        </div>

        <!-- details drawer - can be collapsed -->
        <div class="komet-concept-section-panel-details">

            <!-- loop through the description attributes -->
            <% description[:attributes].each_with_index do |attribute, attribute_index| %>

                <% if attribute_index > 0 %>
                    <hr class="komet-concept-details-hr" />
                <% end %>

                <div class="komet-row">

                    <%
                       if attribute[:label] == 'UUID'
                           tag_details = 'class="komet-concept-description-details-name komet-context-menu" data-menu-type="concept" data-menu-uuid="' + description[:description_id] + '" data-menu-js-object="' + @viewer_id + '"'
                       else
                           tag_details = 'class="komet-concept-description-details-name"'
                       end
                    %>

                    <div <%= raw tag_details %>>
                        <b><%= attribute[:label] %>:</b> <%= attribute[:text] %>
                    </div>


                    <% if attribute[:label] == 'Dialect' %>

                        <div class="komet-concept-description-details-item">
                            <b>Acceptability:</b> <%= attribute[:acceptability_text] %>
                        </div>

                    <% end %>

                    <div class="komet-concept-description-details-item">
                        <b>State:</b> <%= attribute[:state] %>
                    </div>

                    <div class="komet-concept-description-details-item">
                        <b>Time:</b> <%= attribute[:time] %>
                    </div>

                    <div class="komet-concept-description-details-item">
                        <b>Author:</b> <%= attribute[:author] %>
                    </div>

                    <div class="komet-concept-description-details-item">
                        <b>Module:</b> <%= attribute[:module] %>
                    </div>

                    <div class="komet-concept-description-details-item">
                        <b>Path:</b> <%= attribute[:path] %>
                    </div>
                </div>

            <% end %>

            <% if description[:nested_properties] %>

                <!-- loop through the description nested properties -->
                <% description[:nested_properties][:data].each_with_index do |property, property_index| %>

                    <hr class="komet-concept-details-hr" />

                    <div class="komet-row">

                        <div class="komet-concept-description-details-name">
                            <b><%= property[:sememe_name] %></b>
                        </div>

                        <% property[:columns].each do |column_id, column_data| %>

                            <div class="komet-concept-description-details-item">
                                <b><%= description[:nested_properties][:field_info][column_id][:name] %>:</b>

                                <!-- if this row has a display value show that in place of the row data and put a tooltip to show the row data, otherwise just show the data -->
                                <% if column_data[:display] == '' %>

                                    <%= column_data[:data] %>

                                <% else %>

                                    <span class="komet-context-menu" data-menu-js-object="<%= @viewer_id %>" data-menu-type="sememe" data-menu-uuid="<%= column_data[:data] %>" title="<%= column_data[:data] %>">
                                        <%= column_data[:display] %>
                                    </span>

                                <% end %>
                            </div>

                        <% end %>

                    </div>

                <% end %>
            <% end %>

        </div>

    </div>

<% end %>